"""
HsiaoEye — verify every published article has its OG card on disk.

When you add a new article and forget to run `python _gen_og_images.py`,
the `<meta property="og:image" content="…/assets/og/<slug>.png">` points
to a 404 — link previews on social platforms (Facebook, X, LINE,
Threads, Telegram, Slack) all render the broken-image placeholder.
This check catches it before the article ships.

Scope:
  - Every slug in DN.ARTICLES that is NOT in DN.STUB_SLUGS must have
    a file at /assets/og/<slug>.png
  - Static pages (/about, /tools, /blog/, etc.) get a slug-style check
    too: /assets/og/<slug>.png OR a documented site-wide fallback.

Exit codes:
  0   pass — all OG cards present
  1   fail — at least one slug missing its card
"""
from __future__ import annotations

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
OG_DIR = os.path.join(ROOT, 'assets', 'og')

STATIC_OG_SLUGS = ['home', 'about', 'tools', 'notes', 'privacy', 'blog', 'topics']


def parse_catalog():
    with open(os.path.join(ROOT, 'blog', 'blog-shared.js'), encoding='utf-8') as f:
        js = f.read()
    m = re.search(r'DN\.ARTICLES\s*=\s*\[(.*?)\];', js, re.DOTALL)
    slugs = set(re.findall(r"slug:\s*'([^']+)'", m.group(1))) if m else set()
    stub_m = re.search(r'DN\.STUB_SLUGS\s*=\s*new\s+Set\(\s*\[([\s\S]*?)\]', js)
    stubs = set(re.findall(r"'([^']+)'", stub_m.group(1))) if stub_m else set()
    return sorted(slugs - stubs)


def type_names(obj: dict) -> set[str]:
    value = obj.get('@type')
    if isinstance(value, list):
        return {str(x) for x in value}
    return {str(value)} if value else set()


def meta_content(src: str, key: str, attr: str = 'property') -> str:
    m = re.search(rf'<meta\s+{attr}="{re.escape(key)}"\s+content="([^"]*)"\s*/?>', src, re.I)
    return m.group(1) if m else ''


def public_html_paths(published: list[str]) -> list[str]:
    paths = [
        'index.html', 'about.html', 'tools.html', 'notes.html', 'privacy.html',
        'blog/index.html', 'blog/topics.html',
        'en/index.html', 'en/about.html', 'en/tools.html', 'en/notes.html', 'en/privacy.html',
        'en/blog/index.html', 'en/blog/topics.html',
    ]
    for slug in published:
        paths.append(f'blog/{slug}.html')
        paths.append(f'en/blog/{slug}.html')
    return paths


def bad_alt(value: str) -> bool:
    value = (value or '').strip()
    return len(value) < 8 or '\ufffd' in value or '????' in value


def jsonld_article_images(src: str) -> list[str]:
    images = []
    for raw in re.findall(r'<script\s+type="application/ld\+json"[^>]*>(.*?)</script>', src, re.S):
        try:
            data = json.loads(raw.strip())
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        if type_names(data) & {'Article', 'BlogPosting', 'MedicalScholarlyArticle'}:
            image = data.get('image')
            if isinstance(image, str):
                images.append(image)
            elif isinstance(image, list):
                images.extend(str(x) for x in image)
            elif isinstance(image, dict) and image.get('url'):
                images.append(str(image.get('url')))
    return images


def main():
    if not os.path.isdir(OG_DIR):
        print(f'[FAIL] OG directory missing: {OG_DIR}')
        return 1

    published = parse_catalog()
    missing_article = [s for s in published if not os.path.isfile(os.path.join(OG_DIR, s + '.png'))]
    missing_static = [s for s in STATIC_OG_SLUGS if not os.path.isfile(os.path.join(OG_DIR, s + '.png'))]

    issues = 0
    if missing_article:
        print(f'[FAIL] {len(missing_article)} published article(s) missing OG card '
              f'at /assets/og/<slug>.png:')
        for s in missing_article:
            print(f'  - {s}')
        issues += len(missing_article)

    if missing_static:
        # v37.43 — static pages now have per-page OG cards generated by
        # _gen_og_images.py STATIC_OG_PAGES. Missing one indicates the
        # generator hasn't been re-run after adding a static page.
        print(f'[FAIL] {len(missing_static)} static page(s) missing OG card:')
        for s in missing_static:
            print(f'  - {s}')
        issues += len(missing_static)

    mismatched_meta = []
    mismatched_jsonld = []
    missing_alt = []
    for slug in published:
        path = os.path.join(ROOT, 'blog', slug + '.html')
        if not os.path.isfile(path):
            continue
        with open(path, encoding='utf-8') as f:
            src = f.read()
        expected = f'https://hsiao.chendermatologist.com/assets/og/{slug}.png'
        og_image = meta_content(src, 'og:image')
        twitter_image = meta_content(src, 'twitter:image', attr='name')
        if og_image != expected:
            mismatched_meta.append(f'{slug}: og:image {og_image!r} != {expected!r}')
        if twitter_image != expected:
            mismatched_meta.append(f'{slug}: twitter:image {twitter_image!r} != {expected!r}')
        images = jsonld_article_images(src)
        if expected not in images:
            mismatched_jsonld.append(f'{slug}: Article JSON-LD image must include {expected}')

    for rel in public_html_paths(published):
        path = os.path.join(ROOT, rel)
        if not os.path.isfile(path):
            continue
        with open(path, encoding='utf-8') as f:
            src = f.read()
        if meta_content(src, 'og:image') and bad_alt(meta_content(src, 'og:image:alt')):
            missing_alt.append(f'{rel}: missing/weak og:image:alt')
        if meta_content(src, 'twitter:image', attr='name') and bad_alt(meta_content(src, 'twitter:image:alt', attr='name')):
            missing_alt.append(f'{rel}: missing/weak twitter:image:alt')

    if mismatched_meta:
        print('[FAIL] Published article social image tags are not using their per-article OG cards:')
        for item in mismatched_meta:
            print('  - ' + item)
        issues += len(mismatched_meta)

    if mismatched_jsonld:
        print('[FAIL] Published article JSON-LD image fields are not using their per-article OG cards:')
        for item in mismatched_jsonld:
            print('  - ' + item)
        issues += len(mismatched_jsonld)

    if missing_alt:
        print('[FAIL] Public pages with social images must include descriptive image alt metadata:')
        for item in missing_alt:
            print('  - ' + item)
        issues += len(missing_alt)

    if not missing_article and not missing_static and not mismatched_meta and not mismatched_jsonld and not missing_alt:
        print(f'[OK] OG image audit passed — all {len(published)} articles '
              f'+ {len(STATIC_OG_SLUGS)} static pages have /assets/og/<slug>.png '
              f'on disk and wired into social + Article JSON-LD metadata')

    if issues:
        print()
        print('Fix missing files:  python _gen_og_images.py')
        print('Fix metadata wiring: python _gen_serp_meta.py && python _gen_en_pages.py && python _gen_csp_hashes.py')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
