#!/usr/bin/env python
"""Generate the deployment-local content fallback used by public API routes."""
from __future__ import annotations

import json
from pathlib import Path

SOURCE = Path("assets/search-index.json")
TARGET = Path("api/_content_snapshot.js")


def main() -> None:
    rows = json.loads(SOURCE.read_text(encoding="utf-8"))
    by_slug: dict[str, dict[str, dict]] = {}
    for row in rows:
        slug = str(row.get("slug", "")).strip()
        lang = str(row.get("lang", "")).strip()
        if slug and lang:
            by_slug.setdefault(slug, {})[lang] = row

    articles = []
    for slug, variants in by_slug.items():
        zh = variants.get("zh-Hant-TW")
        if not zh:
            continue
        en = variants.get("en")
        articles.append({
            "slug": slug,
            "title": zh.get("title", ""),
            "title_en": en.get("title", "") if en else "",
            "tag": zh.get("tag", ""),
            "tag_en": en.get("tag", "") if en else "",
            "date": zh.get("date", "2026-01-01"),
            "updated": zh.get("updated") or zh.get("date", "2026-01-01"),
            "cat": zh.get("cat", "myth"),
            "has_en": bool(en),
            "description": zh.get("snippet", ""),
        })

    articles.sort(key=lambda item: (item["updated"], item["date"], item["slug"]), reverse=True)
    payload = json.dumps(articles, ensure_ascii=False, separators=(",", ":"))
    output = (
        "// Generated by _gen_api_content_snapshot.py. Do not edit by hand.\n"
        f"export const FALLBACK_ARTICLES = Object.freeze({payload});\n"
    )
    TARGET.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET} ({len(articles)} published articles)")


if __name__ == "__main__":
    main()
