#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
HsiaoEye — generate SHA-256 hashes of every inline <script> + <style> tag
across the static HTML, then write them into middleware.js so the deployed
CSP can use the actual hash list (`'sha256-...'`) instead of `'unsafe-inline'`.

Run as a build step BEFORE `git push` (also wired into quality.yml).

This is the practical alternative to runtime nonce injection: every inline
tag we control gets its hash listed in the CSP, so the browser allows JUST
those exact byte sequences to execute. Any reflected-XSS injected <script>
will have a different hash → blocked.

Limitations:
  - Edited inline content (admin WYSIWYG) doesn't ship inline JS, so this
    is fine.
  - Third-party tags (GTM, GA, AdSense) aren't inline — they're loaded by
    src= and protected by 'self'/host allowlist, not hashes.
  - When you edit an inline <script>, run this script + redeploy. Forgotten?
    Browser blocks the script — site partially broken, fix is one redeploy.

Output: rewrites the `INLINE_HASHES` constant in middleware.js.
Idempotent.
"""
import os, re, hashlib, base64, glob

ROOT = os.path.dirname(os.path.abspath(__file__))

INLINE_SCRIPT_RE = re.compile(
    r'<script(?![^>]*\bsrc=)([^>]*)>(.*?)</script>',
    re.DOTALL | re.IGNORECASE,
)
INLINE_STYLE_RE = re.compile(
    r'<style([^>]*)>(.*?)</style>',
    re.DOTALL | re.IGNORECASE,
)


def sha256_b64(content: bytes) -> str:
    h = hashlib.sha256(content).digest()
    return base64.b64encode(h).decode('ascii')


def collect_hashes():
    script_hashes = set()
    style_hashes  = set()

    for pattern in ['*.html', 'blog/*.html', 'en/*.html', 'en/blog/*.html', 'tools/*.html']:
        for path in glob.glob(os.path.join(ROOT, pattern)):
            try:
                with open(path, 'r', encoding='utf-8') as f:
                    html = f.read()
            except Exception:
                continue

            for m in INLINE_SCRIPT_RE.finditer(html):
                # Hash the EXACT inner-text bytes (browsers normalise nothing)
                body = m.group(2).encode('utf-8')
                script_hashes.add(sha256_b64(body))

            for m in INLINE_STYLE_RE.finditer(html):
                body = m.group(2).encode('utf-8')
                style_hashes.add(sha256_b64(body))

    return sorted(script_hashes), sorted(style_hashes)


def rewrite_middleware(script_hashes, style_hashes):
    mw_path = os.path.join(ROOT, 'middleware.js')
    with open(mw_path, 'r', encoding='utf-8') as f:
        src = f.read()

    script_arr = ',\n  '.join(f"'sha256-{h}'" for h in script_hashes)
    style_arr  = ',\n  '.join(f"'sha256-{h}'" for h in style_hashes)

    block = f"""// AUTO-GENERATED by _gen_csp_hashes.py — DO NOT EDIT MANUALLY
// Re-run after editing any inline <script> or <style> in the HTML.
// Hashes match SHA-256 of the EXACT inner-text bytes of each tag.
const INLINE_SCRIPT_HASHES = [
  {script_arr}
];
const INLINE_STYLE_HASHES = [
  {style_arr}
];
// END AUTO-GENERATED"""

    # Replace any existing block, or insert after the imports
    pattern = re.compile(
        r'// AUTO-GENERATED by _gen_csp_hashes\.py.*?// END AUTO-GENERATED',
        re.DOTALL,
    )
    if pattern.search(src):
        new_src = pattern.sub(block, src)
    else:
        # Insert before `export const config`
        new_src = re.sub(
            r"(export const config = \{)",
            block + "\n\n\\1",
            src,
            count=1,
        )

    if new_src != src:
        with open(mw_path, 'w', encoding='utf-8') as f:
            f.write(new_src)
        return True
    return False


def main():
    script_hashes, style_hashes = collect_hashes()
    print(f'Collected {len(script_hashes)} script hashes, {len(style_hashes)} style hashes')
    changed = rewrite_middleware(script_hashes, style_hashes)
    if changed:
        print(f'middleware.js updated.')
    else:
        print(f'middleware.js already up to date.')


if __name__ == '__main__':
    main()
