/**
 * Vercel Edge Middleware — sets enforce-mode CSP + Trusted Types headers.
 *
 * v33: Real hash-based CSP. Build step `_gen_csp_hashes.py` walks every
 * .html file, computes SHA-256 of every inline <script> and <style> body,
 * then writes the hash list below. The `Content-Security-Policy` header
 * lists those exact hashes (`'sha256-…'`) instead of `'unsafe-inline'`,
 * so reflected-XSS injected scripts are byte-different and get blocked.
 *
 * To regenerate hashes after editing any inline tag:
 *   python _gen_csp_hashes.py
 *   git commit middleware.js -m "ci: refresh CSP hashes"
 *
 * Note: 3rd-party scripts (GTM/GA) are NOT inline — they're `<script src=…>`
 * and protected by the `script-src 'self' <hosts>` allowlist instead.
 */

// AUTO-GENERATED by _gen_csp_hashes.py — DO NOT EDIT MANUALLY
// Re-run after editing executable inline <script> content in HTML.
// Each route carries only its own hashes to keep response headers bounded.
const INLINE_SCRIPT_HASHES_BY_ROUTE = Object.freeze({
  "/": [
    "sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=",
    "sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=",
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w="
  ],
  "/404": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-lkrkVSbw6DPSirRpM8QQgr/fHyMXPeUvYXtzaI8PRg4=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/404.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-lkrkVSbw6DPSirRpM8QQgr/fHyMXPeUvYXtzaI8PRg4=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/about": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/about.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/admin": [
    "sha256-BTTch/g8ZDTDiTevAUQI3fSsrdihsvqxd1E5q5MyLDo=",
    "sha256-jmHC5zllRJT3+JHmgKDznjmRz/wFNfdXf4Xh8xCxVDo=",
    "sha256-n6/K9tAN+B37mXGJmevpqK/IVChiBt50RWZnGp4Ybr8=",
    "sha256-penY6mDfJl/SICorSzPu10UZVEGn18j4fTKFWbJYt+U="
  ],
  "/admin.html": [
    "sha256-BTTch/g8ZDTDiTevAUQI3fSsrdihsvqxd1E5q5MyLDo=",
    "sha256-jmHC5zllRJT3+JHmgKDznjmRz/wFNfdXf4Xh8xCxVDo=",
    "sha256-n6/K9tAN+B37mXGJmevpqK/IVChiBt50RWZnGp4Ybr8=",
    "sha256-penY6mDfJl/SICorSzPu10UZVEGn18j4fTKFWbJYt+U="
  ],
  "/blog/cataract-comprehensive-guide": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU=",
    "sha256-t8kfezZiJi/C/4g/MmlkV5aBEzyHuHbrib4CBkBzmJI="
  ],
  "/blog/cataract-comprehensive-guide.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU=",
    "sha256-t8kfezZiJi/C/4g/MmlkV5aBEzyHuHbrib4CBkBzmJI="
  ],
  "/blog/cataract-surgery-faq": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/cataract-surgery-faq.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/cataract-surgery-selection": [
    "sha256-MDezNRH+Siyd6RYBjB3sq2CM10V8GlxjqaaiznM8l/4="
  ],
  "/blog/cataract-surgery-selection.html": [
    "sha256-MDezNRH+Siyd6RYBjB3sq2CM10V8GlxjqaaiznM8l/4="
  ],
  "/blog/contact-lens-safety": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/contact-lens-safety.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/diabetic-retinopathy-dementia-trinetx-cohort": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/diabetic-retinopathy-dementia-trinetx-cohort.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/dims-pediatric-myopia-control": [
    "sha256-49j4MRi/n64QCzBSEKbl919jO7nj63UZEZ/ekLA0Xsg=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/dims-pediatric-myopia-control.html": [
    "sha256-49j4MRi/n64QCzBSEKbl919jO7nj63UZEZ/ekLA0Xsg=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/dry-eye-myths": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/dry-eye-myths.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/dry-eye-symptom-sign-discordance-dream": [
    "sha256-dcRU+lSI0geJtoQbrYxg9/obmFcIYoqn2io2dwI0P04=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/dry-eye-symptom-sign-discordance-dream.html": [
    "sha256-dcRU+lSI0geJtoQbrYxg9/obmFcIYoqn2io2dwI0P04=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/floaters-retinal-detachment": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/floaters-retinal-detachment.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/glaucoma-comprehensive-guide": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-bfZ97Dp+6r2pGTUtWWbPWs9FoGddbOr8a1slzXxgA7M=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/glaucoma-comprehensive-guide.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-bfZ97Dp+6r2pGTUtWWbPWs9FoGddbOr8a1slzXxgA7M=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/glaucoma-treatment-selection": [
    "sha256-Zz2HfZ2XIEpwJj4tER+VY/ya8XpiIuiJ9WCHJCDVvKk="
  ],
  "/blog/glaucoma-treatment-selection.html": [
    "sha256-Zz2HfZ2XIEpwJj4tER+VY/ya8XpiIuiJ9WCHJCDVvKk="
  ],
  "/blog/glaucoma-warnings": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/glaucoma-warnings.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/hzo-stromal-keratitis-zeds-lessons": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/hzo-stromal-keratitis-zeds-lessons.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/index.html": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/lacrimal-gland-tumor": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/lacrimal-gland-tumor.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/monitoring-myopia-ser-vs-axial-length": [
    "sha256-MhBhTNaFIzcEEpGPZbPqtnc3AXYvHdx6f+jTWTimZ1s=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/monitoring-myopia-ser-vs-axial-length.html": [
    "sha256-MhBhTNaFIzcEEpGPZbPqtnc3AXYvHdx6f+jTWTimZ1s=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg="
  ],
  "/blog/ophthalmic-trauma-overlooked-burden": [
    "sha256-Tq9UQ+o7cjuXuQjGwYJBWW7lY/7xWwImS6s919sv46M=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ="
  ],
  "/blog/ophthalmic-trauma-overlooked-burden.html": [
    "sha256-Tq9UQ+o7cjuXuQjGwYJBWW7lY/7xWwImS6s919sv46M=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ="
  ],
  "/blog/osa-amd-systematic-review-2026": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/osa-amd-systematic-review-2026.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pediatric-high-myopia-maculopathy-progression": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pediatric-high-myopia-maculopathy-progression.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pediatric-myopia-control": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pediatric-myopia-control.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pterygium-surgery-fixation-methods-2026-nma": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/pterygium-surgery-fixation-methods-2026-nma.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/red-eye-conjunctivitis": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/red-eye-conjunctivitis.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/refractory-noninfectious-uveitis-biologics-rubi-trial": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/refractory-noninfectious-uveitis-biologics-rubi-trial.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/thyroid-eye-disease": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/thyroid-eye-disease.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/topics": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/topics.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/toric-iol-astigmatism-cataract-review": [
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/blog/toric-iol-astigmatism-cataract-review.html": [
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/about": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/about.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/cataract-comprehensive-guide": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU=",
    "sha256-t8kfezZiJi/C/4g/MmlkV5aBEzyHuHbrib4CBkBzmJI="
  ],
  "/en/blog/cataract-comprehensive-guide.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU=",
    "sha256-t8kfezZiJi/C/4g/MmlkV5aBEzyHuHbrib4CBkBzmJI="
  ],
  "/en/blog/cataract-surgery-faq": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/cataract-surgery-faq.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/cataract-surgery-selection": [
    "sha256-MDezNRH+Siyd6RYBjB3sq2CM10V8GlxjqaaiznM8l/4=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/cataract-surgery-selection.html": [
    "sha256-MDezNRH+Siyd6RYBjB3sq2CM10V8GlxjqaaiznM8l/4=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/contact-lens-safety": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/contact-lens-safety.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/diabetic-retinopathy-dementia-trinetx-cohort": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/diabetic-retinopathy-dementia-trinetx-cohort.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/dims-pediatric-myopia-control": [
    "sha256-49j4MRi/n64QCzBSEKbl919jO7nj63UZEZ/ekLA0Xsg=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/dims-pediatric-myopia-control.html": [
    "sha256-49j4MRi/n64QCzBSEKbl919jO7nj63UZEZ/ekLA0Xsg=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/dry-eye-myths": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/dry-eye-myths.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/dry-eye-symptom-sign-discordance-dream": [
    "sha256-dcRU+lSI0geJtoQbrYxg9/obmFcIYoqn2io2dwI0P04=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/dry-eye-symptom-sign-discordance-dream.html": [
    "sha256-dcRU+lSI0geJtoQbrYxg9/obmFcIYoqn2io2dwI0P04=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/floaters-retinal-detachment": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/floaters-retinal-detachment.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/glaucoma-comprehensive-guide": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-bfZ97Dp+6r2pGTUtWWbPWs9FoGddbOr8a1slzXxgA7M=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/glaucoma-comprehensive-guide.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-bfZ97Dp+6r2pGTUtWWbPWs9FoGddbOr8a1slzXxgA7M=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/glaucoma-treatment-selection": [
    "sha256-Zz2HfZ2XIEpwJj4tER+VY/ya8XpiIuiJ9WCHJCDVvKk=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/glaucoma-treatment-selection.html": [
    "sha256-Zz2HfZ2XIEpwJj4tER+VY/ya8XpiIuiJ9WCHJCDVvKk=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/glaucoma-warnings": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/glaucoma-warnings.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/hzo-stromal-keratitis-zeds-lessons": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/hzo-stromal-keratitis-zeds-lessons.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/index.html": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/lacrimal-gland-tumor": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/lacrimal-gland-tumor.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/monitoring-myopia-ser-vs-axial-length": [
    "sha256-MhBhTNaFIzcEEpGPZbPqtnc3AXYvHdx6f+jTWTimZ1s=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/monitoring-myopia-ser-vs-axial-length.html": [
    "sha256-MhBhTNaFIzcEEpGPZbPqtnc3AXYvHdx6f+jTWTimZ1s=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/ophthalmic-trauma-overlooked-burden": [
    "sha256-Tq9UQ+o7cjuXuQjGwYJBWW7lY/7xWwImS6s919sv46M=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/ophthalmic-trauma-overlooked-burden.html": [
    "sha256-Tq9UQ+o7cjuXuQjGwYJBWW7lY/7xWwImS6s919sv46M=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8="
  ],
  "/en/blog/osa-amd-systematic-review-2026": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/osa-amd-systematic-review-2026.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pediatric-high-myopia-maculopathy-progression": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pediatric-high-myopia-maculopathy-progression.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pediatric-myopia-control": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pediatric-myopia-control.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pterygium-surgery-fixation-methods-2026-nma": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/pterygium-surgery-fixation-methods-2026-nma.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-jXII38uaZ3tdYK74kWa7fBCsC/7eUz1rFbzO8Wq7cGQ=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/red-eye-conjunctivitis": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/red-eye-conjunctivitis.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/refractory-noninfectious-uveitis-biologics-rubi-trial": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/refractory-noninfectious-uveitis-biologics-rubi-trial.html": [
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/thyroid-eye-disease": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/thyroid-eye-disease.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/topics": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/topics.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/toric-iol-astigmatism-cataract-review": [
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/blog/toric-iol-astigmatism-cataract-review.html": [
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/index.html": [
    "sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=",
    "sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=",
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w="
  ],
  "/en/notes": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/notes.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/privacy": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/privacy.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/tools": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/en/tools.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/index.html": [
    "sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=",
    "sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=",
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w="
  ],
  "/notes": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/notes.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/offline": [
    "sha256-/C0/8ZNCQSu3tvAoIO0KEc9aFCPYw3q90BZZ/tmC0rw=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/offline.html": [
    "sha256-/C0/8ZNCQSu3tvAoIO0KEc9aFCPYw3q90BZZ/tmC0rw=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/privacy": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/privacy.html": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/tools": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/tools.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "/tools/eye-3d": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-tZYv1aRs0L/7xUeIO4o5G2ioW3pcuLUzjZBr/hTrgMs="
  ],
  "/tools/eye-3d.html": [
    "sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=",
    "sha256-tZYv1aRs0L/7xUeIO4o5G2ioW3pcuLUzjZBr/hTrgMs="
  ],
  "__fallback__": [
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-lkrkVSbw6DPSirRpM8QQgr/fHyMXPeUvYXtzaI8PRg4=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "blog": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "blog/": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "en": [
    "sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=",
    "sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=",
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w="
  ],
  "en/": [
    "sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=",
    "sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=",
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w="
  ],
  "en/blog": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ],
  "en/blog/": [
    "sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=",
    "sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=",
    "sha256-erbbMXPjWbfPz6HOaWzw+aJq82UcFYd10sCnSK8qpDg=",
    "sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=",
    "sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=",
    "sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU="
  ]
});
// END AUTO-GENERATED

export const config = {
  matcher: [
    '/((?!api|_next|_vercel|admin|sw\\.js|robots\\.txt|sitemap\\.xml|.*\\.(?:js|css|svg|png|jpg|jpeg|gif|webp|avif|ico|woff2?|xml|json|txt|map)).*)',
  ],
};

function hashesForRequest(req) {
  let pathname = '/';
  try {
    pathname = new URL(req.url).pathname || '/';
  } catch (e) {}
  return INLINE_SCRIPT_HASHES_BY_ROUTE[pathname]
    || INLINE_SCRIPT_HASHES_BY_ROUTE[pathname.replace(/\/+$/, '')]
    || INLINE_SCRIPT_HASHES_BY_ROUTE.__fallback__
    || [];
}

function buildCsp(scriptHashes) {
  // v34.1 fix: Inline `style="…"` attributes are sprinkled across the
  // dynamically-injected DOM (spotlight cards, scroll-to-top, share toolbar,
  // floating TOC, etc). Hash-listing every unique inline style is impractical
  // — they vary at runtime. So style-src KEEPS `'unsafe-inline'` always
  // (low XSS surface — CSS can't run JS). Only script-src moves to hash mode
  // for the real security win against reflected-XSS.
  // FAIL CLOSED: script-src never falls back to unsafe-inline. Unknown routes
  // receive only the 404-page hashes, so an injected script cannot borrow a
  // hash that belongs to an unrelated page.
  const hashSource = scriptHashes.map(h => `'${h}'`).join(' ');
  const scriptSrc = `script-src 'self' ${hashSource} https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms https://cdn.jsdelivr.net`;

  const styleSrc = `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net`;

  return [
    `default-src 'self'`,
    scriptSrc,
    styleSrc,
    `font-src 'self' https://fonts.gstatic.com data:`,
    // v37.4: tightened from `https:` catchall (any HTTPS source) to explicit
    // allowlist. Keeps Google Maps/Photo CDN + Vercel previews working but
    // blocks arbitrary 3rd-party image embeds (privacy + tracking-pixel defense).
    `img-src 'self' data: blob: https://hsiao.chendermatologist.com https://*.vercel.com https://*.vercel.app https://www.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com`,
    `connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://*.clarity.ms https://stats.g.doubleclick.net`,
    `frame-src 'self' https://www.google.com https://www.youtube.com`,
    `frame-ancestors 'self'`,
    `base-uri 'self'`,
    `form-action 'self' mailto:`,
    `object-src 'none'`,
    `manifest-src 'self'`,
    `worker-src 'self'`,
    `require-trusted-types-for 'script'`,
    `trusted-types default hs-policy`,
    `report-uri /api/csp-report`,
    `upgrade-insecure-requests`,
  ].join('; ');
}

export default function middleware(req) {
  const headers = new Headers();
  // v37.30 — vercel.json USED TO ALSO set a `Content-Security-Policy`
  // header on the `/(.*)` wildcard rule with `script-src 'unsafe-inline'`.
  // Vercel applies static headers AFTER middleware, so the loose CSP
  // there silently overwrote this strict hash CSP — defeating the whole
  // `_gen_csp_hashes.py` pipeline. The CSP entry has been removed from
  // vercel.json; this middleware is now the single source of truth for
  // CSP on every HTML response.
  headers.set('Content-Security-Policy', buildCsp(hashesForRequest(req)));
  headers.set('Reporting-Endpoints', 'csp-endpoint="/api/csp-report"');
  headers.set('x-middleware-next', '1');
  return new Response(null, { headers });
}
