/**
 * Vercel Edge Middleware — sets enforce-mode CSP + Trusted Types headers.
 *
 * v33: Real hash-based CSP. Build step `_gen_csp_hashes.py` walks every
 * .html file, computes SHA-256 of every inline <script> and <style> body,
 * then writes the hash list below. The `Content-Security-Policy` header
 * lists those exact hashes (`'sha256-…'`) instead of `'unsafe-inline'`,
 * so reflected-XSS injected scripts are byte-different and get blocked.
 *
 * To regenerate hashes after editing any inline tag:
 *   python _gen_csp_hashes.py
 *   git commit middleware.js -m "ci: refresh CSP hashes"
 *
 * Note: 3rd-party scripts (GTM/GA) are NOT inline — they're `<script src=…>`
 * and protected by the `script-src 'self' <hosts>` allowlist instead.
 */

// AUTO-GENERATED by _gen_csp_hashes.py — DO NOT EDIT MANUALLY
// Re-run after editing any inline <script> or <style> in the HTML.
// Hashes match SHA-256 of the EXACT inner-text bytes of each tag.
const INLINE_SCRIPT_HASHES = [
  'sha256-+/tYeTTS+duaSgTUq7kXhiEYjId82N/gQmL25kJrh08=',
  'sha256-+Jd8GYH9y9/zZLkbV08nWJTqfdyoiMEo3R1M/iLDVaI=',
  'sha256-+Sfevi2Tb4gIa3GKJ37bTegNp6BTIxSYsNrTDlxyRfk=',
  'sha256-/3iM0WqE9quaXPxE5KtGhT/Ik93TTfFlT2SkXuJkFp0=',
  'sha256-/C0/8ZNCQSu3tvAoIO0KEc9aFCPYw3q90BZZ/tmC0rw=',
  'sha256-/e11OwfXBGeUv5R8CwX5gRqC/zRYjwyhPp7mrEf6DZI=',
  'sha256-0LOagZeW6Diem5iHet9yXW9MP+2K5WzVF6O9Sq3MtNE=',
  'sha256-0sD+/0BZ0D6lSvQH5c3hidSqTeNbHYOLoc7MWd34SHk=',
  'sha256-1M4QvYUiKxAVz9EG3b4K2bo26ZZ0tkJsAf42wbkcaZE=',
  'sha256-1PCJKzyrCOvN1lBeGsNPQGFx+jHhrzToCA00u355LiI=',
  'sha256-1jYYNfr2R/J7sUgkDySUUo/xEEjQ/vxQbBONSFKtYv8=',
  'sha256-2O5C+yfWSG90hfzgR25EgRrTIHt+u4XzeaJeWvVLcIM=',
  'sha256-2db6DSkOyIsydPwGgKL1Poy+757kQ4sYmJ7j45Hn8Gk=',
  'sha256-3Uce0CUwt8yRNNla9yuXn8Vo9m++XlZ+3EfEjv8oIH4=',
  'sha256-3al5qQPPcxWEUJhMY3LDrSyxdHocs/+mnR065aFFng4=',
  'sha256-3cf1yIruDAVvMelLXPLTZGlJsRRxEjdIuxucbcxOPbA=',
  'sha256-3uMy4ymmvUd2bC4QRp3KzKD1zbP9khv1vNuPBmXpMG0=',
  'sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=',
  'sha256-49j4MRi/n64QCzBSEKbl919jO7nj63UZEZ/ekLA0Xsg=',
  'sha256-49w34g8EpPq/kUZAE0Svj3ZH0laT/9Z4yJO32h2Iq4k=',
  'sha256-4PXmxtzcIzqNF6wWcen8YL/cY5RpV6+MeK58D2Qu4Io=',
  'sha256-5/kahImV6sm3OPNX9X7i6pU5+KdGDyNC4KuE/uj7/Ew=',
  'sha256-5XGKO/cT1P1fbm1u9s6IpMWmV7c2HA5iYDORig6AfmE=',
  'sha256-5wHbFXerBvWfO8a2xdZhYljbaYUo22Qq++QZ9Shislo=',
  'sha256-608VObtCT5kK1sw2kZZZdg9+1YPHV7xCnbHaxpt1whY=',
  'sha256-6FZchmQRrdAcSKFpLx9nylhiQ7YoBwS0ayuEbjx+RpU=',
  'sha256-6To75dl+r5E0m0v9s5yNJwEdeZKlds7GtQzFIZyhILI=',
  'sha256-6W5sbNb0MgGMoyE5BMNpLqC2sEOzYzbhDiNLgvew3OQ=',
  'sha256-6yRX9F6KWztGF5ia+cGMw2n3C5L7qtqGu926OGgZk88=',
  'sha256-7O5p1cbV3aZB3PNHm6mKihsPo4t+jdS1ejU29YYp828=',
  'sha256-7ZcT1U4h7OWjVv2xrGIsURkow3pKXhF4jNA+MJCtW5w=',
  'sha256-8C4FsZocr3QL9LdEA8B38kQvT5HKlmDefQyrCQlJziA=',
  'sha256-8PfbOLWo8Ehmm459C6dKPUYxP9yXrtA6oOExNkd5puo=',
  'sha256-8jsCoa90yoRcSdLopODZ++8P7V56QpO/wm8hcaGkMVg=',
  'sha256-9X8Ae8HHm5HkhjYn4toN2y68A11Qp9Ys11gr7BIWPTk=',
  'sha256-9cR9v2gpelGnu60HD66B4DvO8dXu0UKMuS8egl7CtF0=',
  'sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=',
  'sha256-AKi3Tb6E7t4eCaRBU6JmxKT9cxreXPDYkd1Kok8NwiU=',
  'sha256-BP44tfLuzpcAvdBm1KyjojSjaWX+gaVtxjeCdVuNh5Q=',
  'sha256-BYwo7KtU/3ewabOOuYfTtE92vrWeIIr/v+cbn3d0R0s=',
  'sha256-C0SV+Qhwae0xkHTVc2VEwkbG2TMueKu1bSOQlQnypaQ=',
  'sha256-CM5qITStav4dr7/IBxQpeHQitsiV1uncVLuI5SiSrFQ=',
  'sha256-E0NGiQ4JBuqjxsBPxv7MuwyDpcJcWSuUjeAnURx1/DU=',
  'sha256-E0eF8K2BZ533OgzAI9sp7lTHLK0qByEqtOX9eM9Dym8=',
  'sha256-E38q94o/jKaXjZlqj4xE/aCaAGUz16YYfzQAzKLG2Qk=',
  'sha256-EM9wv4OCXTrkLxxeoryKsqmyTEx1jG7n7D4o2G4XUiM=',
  'sha256-G8HVIO7OtuMvSQ596NykfMdyvLCNdsMrY6YPLq0oqkg=',
  'sha256-GKpQe42vqElXybRQMylBrMnjICIrWNQ76LyFY+srkGE=',
  'sha256-GQ+p4Jhg6INHNk8f1B0wON6svDsLVpJ3X4CoubaJdzw=',
  'sha256-Gk9Zr6X2ARFZltwL/IyTbLxsrGKmBZem9BU2z447h6c=',
  'sha256-IKEuB/Ay6v/jNbfjYqIL3XFPTXuGujQkj6Wm2yTY9Bk=',
  'sha256-IKg4UCgLcAT24xQLhe58mcUFxE8aOyOWFiHE+J47vSw=',
  'sha256-IRUQSEtTaGWNLG/1j9IQnjrj875L+x+asG5aLQZ+sP0=',
  'sha256-IXcQwduWuUPAymP4Wz2eMzQ8Uh4Z8AO8C14tLoXDDBE=',
  'sha256-IxteoCHd3CoW/9vUmAMqOWmpp6INsuSiTmJizQ0t6y0=',
  'sha256-J+BMQ6iDZcELTZqmpwUE25fiE6iLEh6rycc5NqPnk9E=',
  'sha256-JVwiXyaMgyZiFt368Nn1EZbzCIQ5s+/Idxd4xSWx6jM=',
  'sha256-KDMS011kEhEd7hRHgOlYvTCTe0/I6xeu53LTcws7km4=',
  'sha256-KhO7iVh2YOH28llKETR4vyPmUDSkMOgqtjbESJOl614=',
  'sha256-LUg94Opff/RtKJ8zfXsplavyzjKZqdiL7ekPdGExpsg=',
  'sha256-LcXR6IhQqkWwPCjnTrkMqGfcnfu10HCO88BspJ1IH1w=',
  'sha256-LuRQQHTIkLigPt9CmAQi9BaJw6b/6+nnduMyu2/gDy4=',
  'sha256-MDezNRH+Siyd6RYBjB3sq2CM10V8GlxjqaaiznM8l/4=',
  'sha256-MRotISVRR//+iE8C6WB6OL4lFRjZGSJBEo5Q0jNzRMs=',
  'sha256-MhBhTNaFIzcEEpGPZbPqtnc3AXYvHdx6f+jTWTimZ1s=',
  'sha256-Mu9vubW4k8v9cphDAVuhT0Cngss3855L6dCAAeClbjk=',
  'sha256-NiP7TawBXRE9ktFv2SIwKB6TNt5l/ulFSwXvfv8t+48=',
  'sha256-NnksQj8Y768U6y63AfyZD7/u4lfy9Pp8lwLmQXyMCxs=',
  'sha256-NtBCpnq9wsREVBLFt0im6+pemNROJwVC5j6JK54sCqY=',
  'sha256-ORgc47af5dKMbeTzdSMmejPvMBTPd8gBDQIH+iQKdto=',
  'sha256-PPqAcMPcTNGJ/+058HoBtM8nAFh3mdhr44OvEVbXcyM=',
  'sha256-Qwt/36+2cMXEUcgB+zjAo52UZ6CGrhFEC5M09AgZzAs=',
  'sha256-R9KRhMBjNU2H52FgTNx/hAAkzF5bKn8BPMp68+vjnx4=',
  'sha256-RRfNCGFMM+EgP7J0S5uHxTKpWxQG4ENeelof9EK6gRM=',
  'sha256-Rn3+yvInd6TbAjZE4vl7kO8VSx1zyFTjMfmcTjf8yxo=',
  'sha256-S35/m0XNBwns2U2thlxsM0XiqAfQyftZY2I96WLuGA4=',
  'sha256-SKfNvJugfuBFKRB/DKGnU0swQCork5pj+2yYuDnDuZ8=',
  'sha256-SMYEsjh0kRKpezLRMowcBtlG3UCUkDcXxsqhBWWsTUQ=',
  'sha256-SWBDA66D/NskPKe6OZz4afKp46YKVAIMMkGnqhIso1E=',
  'sha256-TAwYqLWvHFoyN99nMOp6CESXXMnNdw74svNpKsQXWxA=',
  'sha256-VPv9WhRVVOxWE2o3xXEJ0NbKNXdnDLfJmyfIwExTsdE=',
  'sha256-VgS1rsSbN3CHjoqhB3tgcaX5T6s7fAmgN738vgxJ5Mc=',
  'sha256-VoXSspcfPMjXA5nENFIr7QweU7ij6ahfBFT+c92egS0=',
  'sha256-VsJGA+n+t/UhZD8Vf4JuGi0E9Q3ErirYOOdbcN0Rpt8=',
  'sha256-WI+72UI/0RMQ0dP9din6h15E5cWWxAXu+l4NZChsTCA=',
  'sha256-WOonlLhkrWnyQuJd13835o3Elqbgd/vPLKu+yS3kT6s=',
  'sha256-X4fIzhXOI/v5K4vCvdXdw8OJ+qHisneTV5QDESMMUfU=',
  'sha256-X5RECgeDB2ylXnf0CdlwS1EatLKuGCyjD0j2o+DH2Gk=',
  'sha256-XMJNTZdwGpH5U+dSxlZ31cUuHayalT02lpOznG1Dulw=',
  'sha256-XcBRyydoaKyaqj8sXlhj8olUH/HUBnZzCr1nN9DxhcM=',
  'sha256-XyTwqlrNo+8WMh6vqRckg+bF++sENUdIQQCPFXpAStY=',
  'sha256-YXURvWnGElWig6rvXvmDCpHSLWUeoB97mbIJfJXuYg0=',
  'sha256-Zfz2IazmaEEVqzx5VZgHjq2FsYZVCuunqBgr8v6FI1E=',
  'sha256-ZgycaOHiMW2mBlrcNY/tAktZ3qaV2q7itgf6ydBfnG4=',
  'sha256-Zz2HfZ2XIEpwJj4tER+VY/ya8XpiIuiJ9WCHJCDVvKk=',
  'sha256-aFnuZPdJcRqVxb64b3QXgMx2NVQcaICf94qbBSZPTcQ=',
  'sha256-aL0KvDrtGVtaKU5aPPPAl16a54t2oei40fR6UW15vks=',
  'sha256-anfQMa4PR7hJMlZYn1pp86wIZBrOVREFJyizy77Ah7Y=',
  'sha256-bZcNVt9jv37K2y4BDmnN06PZve8qsmubblxeR3YuPcs=',
  'sha256-baJQ8qooqyZ+Dbl78iinnhu+zcAsS7fdYZHAp2R5xl8=',
  'sha256-bfZ97Dp+6r2pGTUtWWbPWs9FoGddbOr8a1slzXxgA7M=',
  'sha256-bpb7grnJfMovCKwA8/LKnrWI1dba2ATGx35GqjKbvNo=',
  'sha256-cJn7Y3ReeFKbrrH6hm0pkqc+dy9+s3xPolaKUdeAcD4=',
  'sha256-cNTdio5jh1+LYTAFS7Rvgtd/2oKxFaxs9vzPMzFtc7Y=',
  'sha256-cgqdnTrItAoXdYElKFTWgD5aLkAY3YumNCXKLz2TzqI=',
  'sha256-chO1xe7dzqiOuUuF9fIaBaefC7CFmdSnNLfzxXarXwo=',
  'sha256-czIWIzoo47Ln46V98KwP2gt4pzeYVm6QKRbt74vQLb0=',
  'sha256-d9/FQhSbsQjXl0fi1n4E6mZCIHedgEdNQz2/kGPoZS4=',
  'sha256-dQq21IUCUPHLvtoi3qXf5oaVdcpymhx5W61PYCrz9dk=',
  'sha256-dcRU+lSI0geJtoQbrYxg9/obmFcIYoqn2io2dwI0P04=',
  'sha256-dcTqSF06D5EYmIih0uuvrZ3eHJgrO83X3IQ4SdbYH0M=',
  'sha256-eDCCU1GtWB/22Dlr7NQFrXxScoOhQwG2YeFAGD6su8g=',
  'sha256-exQN9yYCJFYWfFk0Eh9VCA1nqZQIICsaJv0wReGO2QA=',
  'sha256-fB42+jHRxGh57RrBP6h/GbJDx2CwlOPZ+f1Nmq9dS1M=',
  'sha256-fJ4OeBwh3tagf/1Ko2DTi68S7Yzg+IWNe9I52gy4mUg=',
  'sha256-fcv17CsfcCh9WnBj5R5ecLtvbZM2S+AdqxhBRGx/p0E=',
  'sha256-fsmO+6gHw+ks6C9qcsUBlVBcp4V0ZCoMAokm5NPW/Vo=',
  'sha256-gH1g1Ya3hpCBjFhzfPWOsLI2DA98jrdspPsrAocDyKw=',
  'sha256-gciNWwl9JVS6vkt+j6d85ad9vh4sURKAg4qpwgr+8kI=',
  'sha256-hQikEk6cFLQgYxq+wtfSVtDCgjkDhMAHYyd3kWIkUgI=',
  'sha256-hYw1H6XfQIKm5CT4WS3BQQDTykKaS6hdwl2N2pC8QNI=',
  'sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=',
  'sha256-ikFfdYwm6Xhbf67iQaoZsKaXwc6TjDMxnFspzRWD4C4=',
  'sha256-itkwjHaqmboqnTvKxH/4/VTM9SOMipi+On7bEfyFTes=',
  'sha256-jBX9CuvxfQamgrBgMfzBF3/CRlbrhHX9FHx1RfTe5SA=',
  'sha256-jhJWEPibvQvpB26eSP8foC3DpzcTJ8HJPNMySYmp8PM=',
  'sha256-jlYsRDCD6hHpIr1rG7peJ9yd4YjErtZfnLAYYHyxyo0=',
  'sha256-jouhg7yPQGiIpQaGbUmMelnJ79MDsWpi2RrTUaTUp0o=',
  'sha256-jvuXghJ0wPzNn2ZR6EDcf5Kgjy6E+vb5RBOSh1/LKH0=',
  'sha256-jw1bzfSWSLe+3xLjHk42TIlo+B6vjtLlT3AAI+j8DcA=',
  'sha256-jyzN4BhzI8O13G8AjPt8K5l3pXmh+T41oX6qEMgHSwA=',
  'sha256-k3CPIcZ85Fu8IHt25FZ+GR4MJhdzCJCZ4eh9YYd6Czg=',
  'sha256-l0YurB0e1b6foJN01dLwOUTgDXFaakxLRqdTaX+Fdpg=',
  'sha256-lOe+htth569V+H3QKKuI+lXgUcqz6mfG0cSOoPmWlkk=',
  'sha256-lkrkVSbw6DPSirRpM8QQgr/fHyMXPeUvYXtzaI8PRg4=',
  'sha256-lxgSVKop8pfkQWwZbgW2SlvUQ7IPDZ0CFtSKkfEnUIU=',
  'sha256-mF8V189oxtqFL/bSxPwEqkVyNUxu8hheXUs/R3bukP8=',
  'sha256-mMNOCF8KugNmo1xjDVQ2mA1IZxn4c3kk5sMLUaJouXM=',
  'sha256-mW5daSpt15vNd1iNOxICwbqT7G1vnca8w9Q5Hz8OIJc=',
  'sha256-mYyXVau2RGbXn0/yEoz3X5d+oji1TbdRrt64NpD9rWc=',
  'sha256-mdCY75kRbT0RzuYVg3q/SUDBU5ld3fT2Qk9X7qJEFS0=',
  'sha256-n9D+kgd0y9oMNePDV69gw7DRRHF32UBCqcYz8Yq1Z+Q=',
  'sha256-nlq3/8qV7IjtHkjkE8bQQGxbA9HxC9erAKeVsU3VuO4=',
  'sha256-nvBlQhi28ypfxzsAogx933KqcbfCY4btSDQymKmm6+s=',
  'sha256-o0m7i5qotGMfDHFCQwydZfwJGjPwp2RU9UxjKV01F14=',
  'sha256-pGj/mVY7kCaf30iaoFBHdy/j1fo69iWVwNSEPJ2uk9w=',
  'sha256-pKjxkS2xxVTISwk/c1JCbKu7Wb/evK+xrRaJ/Buv+h0=',
  'sha256-pWX5UEHozsgbt54s1mEgOlFRvwavLXcZriZnEl7wdgA=',
  'sha256-penY6mDfJl/SICorSzPu10UZVEGn18j4fTKFWbJYt+U=',
  'sha256-qG6VWputVUr4bSfq1TiB4BKjpCADdkqGMQgVxkigzes=',
  'sha256-qeDIP37XskMeEccIeqHOqzWjUMcjX95/oi3GA0T4Ats=',
  'sha256-qeGIR6p8gYcRhfz/mK0AGipWSelQSR/X1636Bxi97HM=',
  'sha256-rGiBM5cdQnyb16undhBx5h6DuPxP9z4XODuFk+oiriU=',
  'sha256-rNU9E1udm1vPu1/7rfsHBT+ermF0siJVOrrAG/PMurM=',
  'sha256-sszfbe6bfOdrK0J9jANErQMUSoeg2B1ufOBRqDc0jsA=',
  'sha256-t8kfezZiJi/C/4g/MmlkV5aBEzyHuHbrib4CBkBzmJI=',
  'sha256-tPgifUB6KaCWXeiNB27XUmYQzEydj+2Ck3dI3vr11AE=',
  'sha256-uNOHo8BfMFFM53GoWF1QwZGj4VV0Dbjdy3kId3EEh9I=',
  'sha256-uOQjENfZCGv2INIXIGhMpLdH8vxHyV/uuiLogNIEz8s=',
  'sha256-v9vwQ4sN7+LUd1UAI4A1wAuJszPlKW29VgGOm00t1ec=',
  'sha256-vEV1oKsgR9H04XSazwzdmzcRNOYmvuIfv/6TjyIy6Ns=',
  'sha256-vJn8czuC/092WkD5srs/t+HGjUIPzmc+MvG7VyBzCAw=',
  'sha256-vvb6j2atLrVOu06UuBZ260Oz6p2FqXnGVZIegGn7O2I=',
  'sha256-w4QFd1FL0JpL5ig279xOnvGGVxRMZmNGJ0EpA9sNGHY=',
  'sha256-wFpttPsWWgZ/+M9kylaqMqVA39/Yf+Zz3Bg4gHiJM4o=',
  'sha256-xWIxX4RHLYkYpJzMNAOxJpzqz+uXjpQUFz48YVINrUg=',
  'sha256-xeQ4BteJVcfXinlRNoOl1hP/UenUgnYcbnh4QfTd14E=',
  'sha256-xrwY4zIJmH6kHEwYc6HvuSVNNsngzJe0G6MOUIpLorM=',
  'sha256-xtMoNE1WfWwE9cOo1pg+iaZ8fiHNtj6oRjVhWJNBLl8=',
  'sha256-y4TPfSdVjd7zgMLCxrmlG++E76+/ErnxjNryzukVgzI=',
  'sha256-yw3UsrKsOKIoz70hwpQKBW9jK3aEi2jlb/jRjGuhI8w='
];
const INLINE_STYLE_HASHES = [
  'sha256-+PWJ6ceZ9IsMzJbkZxg7S5zWJj84Dc2vgdt7I6ZP784=',
  'sha256-0bHwsFdjjm5tL3cKWoZB7944vi3iaiwYPY9siEV9vcw=',
  'sha256-32UsPi6tERGXUbfgT2OpWPBVojAnVo6sSHgNNg1vJxk=',
  'sha256-4j4vef3FBNbuiKNeDf0U+Kj/pCudneRIyu4fpd8zXdg=',
  'sha256-AYoPBVO7J1VOnerQSR8rLV3sxIm5vwHL/KuFfvqOpfA=',
  'sha256-Aooo5LKwI6ECB5J7ymQ6+YFj3NyPCnB3sTG1Bdf1ORY=',
  'sha256-BvdBD8pd8k4OBgmV8TJUGTBd82DNKZcvN5enLz9DtfY=',
  'sha256-EtZM4Sc2mfUen6gYLniBiUFWWJxQiXi+bYBMpGYpgoY=',
  'sha256-F/poesCfGFAlhGbTbjEvQoLf31j/a9oQ5tZPXj3puH4=',
  'sha256-F4NfWs46CKGM3yAcJyhfxP1NiB+ep3MPMqP9I58vE9c=',
  'sha256-GFPSOoqhFwpzsyJTOwzJjQHFGW/ePi52EfMAcSmmfUs=',
  'sha256-Hs6APTyfIOBpUFZVX/ZkYB4nSrD18A6EmYOTO7MJ5FI=',
  'sha256-I+sCm+05u4bfoTxYON5ywRriq7xTBNSWy2x6k5uarQg=',
  'sha256-JOrtMrPLAmTvQUHaDSxe2lw6oLgWIUUblE8T/QM3IM8=',
  'sha256-KOnh2QAgejmsC8NxaLn2iQ44lhjAoCIh16msu+n0x38=',
  'sha256-KvjvD1CkHPDJDQ6HdMwIxr5j+g6RXypyflYYkUd95EM=',
  'sha256-MYoOx5lW2+0JCSUAVx1bzLeY+QTDmgGx37wiEDD9flQ=',
  'sha256-Q8vert74kcts0zjNLm4HovG1KJB8anMW/YqH37LxzpM=',
  'sha256-R1fkPJ08/7/l3Xir4wwoLPiM4AnJr1MKdHZOGHjgEE0=',
  'sha256-R4oO8HgbIGpZc8rnvGvGvyq2C6DZ0KJe0ERQiBW+A5A=',
  'sha256-RIJz6uRWTHZ404Fve6zAi29nTZYest7qUtTjPq5+t3I=',
  'sha256-RlAe3zc9jwMogA3ScKAg7fzbjjkLpo3yd4KEgqgiZYM=',
  'sha256-SkWxxOmZ/yR0FFdLOsbw1sBVEkEPciO5dl9ck/dO+zs=',
  'sha256-SpJXk45gltoqZ9P/OBT7njdekZu/6bHpu4Z3l3qvegM=',
  'sha256-SuA2CABU2eA+NsT3A0BjxIiK6VaSOvTOWy9LWzmC/qs=',
  'sha256-UnxxarVTOlpGeLl41vIDliHxpPhKqDnlUWHRdjZO6Ro=',
  'sha256-VJHJF3necCGGqihlQznJ3Pd/FAUdxmk7x25Yjmo6aGg=',
  'sha256-WGwB5VT/fNhWNG7xUpVgLtePkF5TSOBfmZC1woY1jCo=',
  'sha256-XyIAg2CN30isFs2MwN8t7mVjxyGQ5eY9RbPixwgl3Ac=',
  'sha256-a+zIAEcYH0l2AALy+E/TcQ37oe99qYvP7d75S262vP0=',
  'sha256-c+Sa286gYxWMjqSeI7vP3NJKCNV6IfFa6yRreqj3aUE=',
  'sha256-dM9Z2Wn5E8zqg2gbFGUuxxJRwFlvd6svNJErybPD1Lc=',
  'sha256-eCR1aoUsZD82UX6tbzCWFdAkSrAOGncqZ/hmMqfTBzE=',
  'sha256-farGoa0q1emAWQxtwOGwVUDwPLmYt8ZejUHTXKKqZvU=',
  'sha256-hHxWm9zVyADoWQqPZuTYym0EJArRLyeRQec+4FxcMbk=',
  'sha256-j8tE3PPoL2ryrtw8eHJ82JlTRTFkw23E0/GjnY12pVo=',
  'sha256-lC0ORRd4So+WjDOdQg81MUBCpdoH4tFdXL6VffijEf4=',
  'sha256-mR6Ww7AONi4e8uujMVeqOj4CA2pOejECfaynbBzls0Q=',
  'sha256-tZrLSGYZvnCrgIIadNzv425t+BD34oU/HZQfXLrhRwM=',
  'sha256-wVlzYzxoS8UAwWdSFPpvoQfJKKq5Wd18NS5kY62KaLo=',
  'sha256-wWl6NKvjzoTVaSfRdsjAp7PQ696Jl5FZL6Jh5wduRqE=',
  'sha256-x3w2AVuOl+53iOFOmxpkTcO1Kj9qFb2jX0Z+0LQGXlA=',
  'sha256-xjE9bIS3lqL2Ef36AzS7Ns4fSiuR9YBdg4ITLKyHqls='
];
// END AUTO-GENERATED

export const config = {
  matcher: [
    '/((?!api|_next|_vercel|admin|sw\\.js|robots\\.txt|sitemap\\.xml|.*\\.(?:js|css|svg|png|jpg|jpeg|gif|webp|avif|ico|woff2?|xml|json|txt|map)).*)',
  ],
};

function buildCsp(hashesActive) {
  // v34.1 fix: Inline `style="…"` attributes are sprinkled across the
  // dynamically-injected DOM (spotlight cards, scroll-to-top, share toolbar,
  // floating TOC, etc). Hash-listing every unique inline style is impractical
  // — they vary at runtime. So style-src KEEPS `'unsafe-inline'` always
  // (low XSS surface — CSS can't run JS). Only script-src moves to hash mode
  // for the real security win against reflected-XSS.
  const scriptSrc = hashesActive
    ? `script-src 'self' ${INLINE_SCRIPT_HASHES.map(h => `'${h}'`).join(' ')} https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms https://cdn.jsdelivr.net`
    : `script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://*.clarity.ms https://cdn.jsdelivr.net`;

  const styleSrc = `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net`;

  return [
    `default-src 'self'`,
    scriptSrc,
    styleSrc,
    `font-src 'self' https://fonts.gstatic.com data:`,
    // v37.4: tightened from `https:` catchall (any HTTPS source) to explicit
    // allowlist. Keeps Google Maps/Photo CDN + Vercel previews working but
    // blocks arbitrary 3rd-party image embeds (privacy + tracking-pixel defense).
    `img-src 'self' data: blob: https://hsiao.chendermatologist.com https://*.vercel.com https://*.vercel.app https://www.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com`,
    `connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://*.clarity.ms https://stats.g.doubleclick.net`,
    `frame-src 'self' https://www.google.com https://www.youtube.com`,
    `frame-ancestors 'self'`,
    `base-uri 'self'`,
    `form-action 'self' mailto:`,
    `object-src 'none'`,
    `manifest-src 'self'`,
    `worker-src 'self'`,
    `require-trusted-types-for 'script'`,
    `trusted-types default hs-policy`,
    `report-uri /api/csp-report`,
    `upgrade-insecure-requests`,
  ].join('; ');
}

export default function middleware(req) {
  const headers = new Headers();
  // v37.30 — vercel.json USED TO ALSO set a `Content-Security-Policy`
  // header on the `/(.*)` wildcard rule with `script-src 'unsafe-inline'`.
  // Vercel applies static headers AFTER middleware, so the loose CSP
  // there silently overwrote this strict hash CSP — defeating the whole
  // `_gen_csp_hashes.py` pipeline. The CSP entry has been removed from
  // vercel.json; this middleware is now the single source of truth for
  // CSP on every HTML response.
  const useHashes = INLINE_SCRIPT_HASHES.length > 0;
  // ENFORCE — prefers hashes when available, falls back to 'unsafe-inline'
  headers.set('Content-Security-Policy', buildCsp(useHashes));
  // REPORT-ONLY mirror — always tightest variant for monitoring
  headers.set('Content-Security-Policy-Report-Only', buildCsp(true));
  headers.set('Reporting-Endpoints', 'csp-endpoint="/api/csp-report"');
  headers.set('x-middleware-next', '1');
  return new Response(null, { headers });
}
