/**
 * Vercel Edge Middleware — sets enforce-mode CSP + Trusted Types headers.
 *
 * v33: Real hash-based CSP. Build step `_gen_csp_hashes.py` walks every
 * .html file, computes SHA-256 of every inline <script> and <style> body,
 * then writes the hash list below. The `Content-Security-Policy` header
 * lists those exact hashes (`'sha256-…'`) instead of `'unsafe-inline'`,
 * so reflected-XSS injected scripts are byte-different and get blocked.
 *
 * To regenerate hashes after editing any inline tag:
 *   python _gen_csp_hashes.py
 *   git commit middleware.js -m "ci: refresh CSP hashes"
 *
 * Note: 3rd-party scripts (GTM/GA) are NOT inline — they're `<script src=…>`
 * and protected by the `script-src 'self' <hosts>` allowlist instead.
 */

// AUTO-GENERATED by _gen_csp_hashes.py — DO NOT EDIT MANUALLY
// Re-run after editing any inline <script> or <style> in the HTML.
// Hashes match SHA-256 of the EXACT inner-text bytes of each tag.
const INLINE_SCRIPT_HASHES = [
  'sha256-+spPJPLh/vX6cNpGg42fztlucbTAFGRf32A33zR0yJY=',
  'sha256-/3iM0WqE9quaXPxE5KtGhT/Ik93TTfFlT2SkXuJkFp0=',
  'sha256-1oxT5UZ9oxT4nHZMypKBiP0tpQevP8eHqAJE6LBCDZQ=',
  'sha256-4+KZQAuj0kFWr9n/nfDdKVqDeUYExYEgtwlmzXyKu0M=',
  'sha256-55Bo9xLNu2nBDUPohAg5LHaUghPvCrro8b5ByHtFm0I=',
  'sha256-7GjDD+1/I9a/gaAod8B74AiVXa8V/o3MMLBmX/Ek9mc=',
  'sha256-A00a+zm6fwfkVq72pWcXpcFkGGole5G5pO9fbp1AJiE=',
  'sha256-AKi3Tb6E7t4eCaRBU6JmxKT9cxreXPDYkd1Kok8NwiU=',
  'sha256-APVM2oGjhu0klvesUOVmPWNuCY1/xt7lsSG0I4ie2oY=',
  'sha256-GakyvAk0GQEFTUdk9AYVRAwXlRVXcApmaiI5jhiFDVc=',
  'sha256-I3en0wz3ASSyaYjBpTa5JT8BauW5xlKdlj3jSF7YzE0=',
  'sha256-ITKpxN4KXcR0MASZsgUsFySLgTDa/doWTlqAn5iLS1M=',
  'sha256-IdtphEEHHnjYRhrKD8odfIU4TTJLJqt4Y1IVFGr2EaA=',
  'sha256-JU17WdBYULN5f5jhZn7efC2uLH32SBxuzM36h2ZEtNk=',
  'sha256-JbY65Pn7tbQST7olzwNV7hw2V0miioWq+P1xGDQxtak=',
  'sha256-N1ShDGgqDNQVALRq3IVkvU/QYcEPJwEVEwNpa3SBrb4=',
  'sha256-ORgc47af5dKMbeTzdSMmejPvMBTPd8gBDQIH+iQKdto=',
  'sha256-OhHlf0kfEemcQV4tLcRAWwT3KOi2i65h6+cFiPfHWmg=',
  'sha256-RmHjLH+Vcw4viP+Ay3rG+Wq8CKJrnTfLZJKQlLEBSO0=',
  'sha256-Rn3+yvInd6TbAjZE4vl7kO8VSx1zyFTjMfmcTjf8yxo=',
  'sha256-X4fIzhXOI/v5K4vCvdXdw8OJ+qHisneTV5QDESMMUfU=',
  'sha256-X5RECgeDB2ylXnf0CdlwS1EatLKuGCyjD0j2o+DH2Gk=',
  'sha256-XLILMHc3auoRTeit5w0BxGsdAELtCSJ9xhUxzwQuwUg=',
  'sha256-XMJNTZdwGpH5U+dSxlZ31cUuHayalT02lpOznG1Dulw=',
  'sha256-Y0ShE1yuwlB8PzUm6RyB99/vFadMZiqfSjvNJGZM2dU=',
  'sha256-aL0KvDrtGVtaKU5aPPPAl16a54t2oei40fR6UW15vks=',
  'sha256-aw9WIv6w7/g9VgZuQx1ZvpdlcIK4c3qTSaosFXscF8c=',
  'sha256-d9/FQhSbsQjXl0fi1n4E6mZCIHedgEdNQz2/kGPoZS4=',
  'sha256-dQq21IUCUPHLvtoi3qXf5oaVdcpymhx5W61PYCrz9dk=',
  'sha256-fmojpWCdqv9lP8TyN/V3R0gUdlQ3A1tWs8j3OYmsJY8=',
  'sha256-haK95xnKsrGjr/r8ImyKMi6OeANjeZ4eYEBRbzUoCUE=',
  'sha256-iU2vvAPzG2ABF09+fbm5PfKdRy7l3sVPFGQcPwF1v44=',
  'sha256-j/iZRnPmsOX6VrL/twSxtqGcMWPegWd29zQ0N2lXTpA=',
  'sha256-jvuXghJ0wPzNn2ZR6EDcf5Kgjy6E+vb5RBOSh1/LKH0=',
  'sha256-jyzN4BhzI8O13G8AjPt8K5l3pXmh+T41oX6qEMgHSwA=',
  'sha256-lkrkVSbw6DPSirRpM8QQgr/fHyMXPeUvYXtzaI8PRg4=',
  'sha256-mW5daSpt15vNd1iNOxICwbqT7G1vnca8w9Q5Hz8OIJc=',
  'sha256-mdCY75kRbT0RzuYVg3q/SUDBU5ld3fT2Qk9X7qJEFS0=',
  'sha256-nqN8z98A8YuDxNRx0ikz0liyHqtn/eIcuq4TREIlXXk=',
  'sha256-nuGmmiiCYDFTpvXLDw6pOoq2DQNyb+Q5uFW1Zc7VYfU=',
  'sha256-oc14LMTc3+PlWxlySAijsD73LxSRdiP9/4fGxD+x2co=',
  'sha256-wq+E/4tFESd/NMOMGNTFKxYdGDpAZsZQaUMxMME6Jpk=',
  'sha256-xtMoNE1WfWwE9cOo1pg+iaZ8fiHNtj6oRjVhWJNBLl8='
];
const INLINE_STYLE_HASHES = [
  'sha256-/+EjQmgqyfzbzphRxWdV28TqjpBpS/PCOgLMub6poNY=',
  'sha256-0bHwsFdjjm5tL3cKWoZB7944vi3iaiwYPY9siEV9vcw=',
  'sha256-2ZIOnMgBC4DX/tqYKqJONpRNPZEmD34imYrJJmsn0EE=',
  'sha256-32UsPi6tERGXUbfgT2OpWPBVojAnVo6sSHgNNg1vJxk=',
  'sha256-4j4vef3FBNbuiKNeDf0U+Kj/pCudneRIyu4fpd8zXdg=',
  'sha256-Aooo5LKwI6ECB5J7ymQ6+YFj3NyPCnB3sTG1Bdf1ORY=',
  'sha256-EtZM4Sc2mfUen6gYLniBiUFWWJxQiXi+bYBMpGYpgoY=',
  'sha256-KOnh2QAgejmsC8NxaLn2iQ44lhjAoCIh16msu+n0x38=',
  'sha256-MYoOx5lW2+0JCSUAVx1bzLeY+QTDmgGx37wiEDD9flQ=',
  'sha256-R4oO8HgbIGpZc8rnvGvGvyq2C6DZ0KJe0ERQiBW+A5A=',
  'sha256-SkWxxOmZ/yR0FFdLOsbw1sBVEkEPciO5dl9ck/dO+zs=',
  'sha256-SuA2CABU2eA+NsT3A0BjxIiK6VaSOvTOWy9LWzmC/qs=',
  'sha256-VJHJF3necCGGqihlQznJ3Pd/FAUdxmk7x25Yjmo6aGg=',
  'sha256-XyIAg2CN30isFs2MwN8t7mVjxyGQ5eY9RbPixwgl3Ac=',
  'sha256-c+Sa286gYxWMjqSeI7vP3NJKCNV6IfFa6yRreqj3aUE=',
  'sha256-eCR1aoUsZD82UX6tbzCWFdAkSrAOGncqZ/hmMqfTBzE=',
  'sha256-farGoa0q1emAWQxtwOGwVUDwPLmYt8ZejUHTXKKqZvU=',
  'sha256-hHxWm9zVyADoWQqPZuTYym0EJArRLyeRQec+4FxcMbk=',
  'sha256-kbfiNtCMC2yWkm5P5TKQe82TEPHxpDlnRCteKmMjl5w=',
  'sha256-wWl6NKvjzoTVaSfRdsjAp7PQ696Jl5FZL6Jh5wduRqE=',
  'sha256-x3w2AVuOl+53iOFOmxpkTcO1Kj9qFb2jX0Z+0LQGXlA=',
  'sha256-xjE9bIS3lqL2Ef36AzS7Ns4fSiuR9YBdg4ITLKyHqls='
];
// END AUTO-GENERATED

export const config = {
  matcher: [
    '/((?!api|_next|_vercel|admin|sw\\.js|robots\\.txt|sitemap\\.xml|.*\\.(?:js|css|svg|png|jpg|jpeg|gif|webp|avif|ico|woff2?|xml|json|txt|map)).*)',
  ],
};

function buildCsp(hashesActive) {
  // When hashes are populated, use them + drop 'unsafe-inline'.
  // Until then, ship the v32 'unsafe-inline' fallback so the site keeps working.
  const scriptSrc = hashesActive
    ? `script-src 'self' ${INLINE_SCRIPT_HASHES.map(h => `'${h}'`).join(' ')} https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://www.clarity.ms https://*.clarity.ms https://cdn.jsdelivr.net`
    : `script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://www.clarity.ms https://*.clarity.ms https://cdn.jsdelivr.net`;

  const styleSrc = hashesActive
    ? `style-src 'self' ${INLINE_STYLE_HASHES.map(h => `'${h}'`).join(' ')} 'unsafe-hashes' https://fonts.googleapis.com https://cdn.jsdelivr.net`
    : `style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net`;

  return [
    `default-src 'self'`,
    scriptSrc,
    styleSrc,
    `font-src 'self' https://fonts.gstatic.com data:`,
    `img-src 'self' data: https: blob:`,
    `connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://*.clarity.ms https://stats.g.doubleclick.net`,
    `frame-src https://www.google.com https://googleads.g.doubleclick.net https://www.youtube.com`,
    `frame-ancestors 'self'`,
    `base-uri 'self'`,
    `form-action 'self' mailto:`,
    `object-src 'none'`,
    `manifest-src 'self'`,
    `worker-src 'self'`,
    `require-trusted-types-for 'script'`,
    `trusted-types default hs-policy`,
    `report-uri /api/csp-report`,
    `upgrade-insecure-requests`,
  ].join('; ');
}

export default function middleware(req) {
  const headers = new Headers();
  // Use hash mode if any hashes are populated (means _gen_csp_hashes.py has run)
  const useHashes = INLINE_SCRIPT_HASHES.length > 0;
  // ENFORCE — prefers hashes when available, falls back to 'unsafe-inline'
  headers.set('Content-Security-Policy', buildCsp(useHashes));
  // REPORT-ONLY mirror — always tightest variant for monitoring
  headers.set('Content-Security-Policy-Report-Only', buildCsp(true));
  headers.set('Reporting-Endpoints', 'csp-endpoint="/api/csp-report"');
  headers.set('x-middleware-next', '1');
  return new Response(null, { headers });
}
