// Visual regression tests for HsiaoEye — Playwright + git-tracked snapshots.
//
// Baselines must be generated by the Ubuntu candidate workflow and reviewed
// by the owner before acceptance. Never auto-update a failing comparison.
//
// Pages covered: home, blog index, five clinical pilots, tools, English mirror.
// Each page is captured at 3 viewports (mobile / tablet / desktop) so we
// catch responsive regressions.

const { test, expect } = require('@playwright/test');
const { request } = require('playwright');
const { previewCookies } = require('../../scripts/preview-access.cjs');

const BASE = process.env.PW_BASE_URL || 'https://hsiao.chendermatologist.com';
let authCookies;
test.beforeAll(async () => { authCookies = await previewCookies(BASE, request); });

const PAGES = [
  { name: 'home',             path: '/' },
  { name: 'blog-index',       path: '/blog/' },
  { name: 'dry-eye-myths',    path: '/blog/dry-eye-myths', article: true },
  { name: 'pediatric-myopia', path: '/blog/pediatric-myopia-control', article: true },
  { name: 'floaters',         path: '/blog/floaters-retinal-detachment', article: true },
  { name: 'lacrimal-gland',   path: '/blog/lacrimal-gland-tumor', article: true },
  { name: 'glaucoma-guide',   path: '/blog/glaucoma-comprehensive-guide', article: true },
  { name: 'tools',            path: '/tools' },
  { name: 'en-home',          path: '/en/' },
];

const VIEWPORTS = [
  { name: 'mobile',  width: 390,  height: 844 },
  { name: 'tablet',  width: 820,  height: 1180 },
  { name: 'desktop', width: 1440, height: 900 },
];

// Block flaky third-party requests that pollute screenshots (analytics
// pixels, ad iframes, font CDN slowness sometimes causes FOIT in shot).
test.beforeEach(async ({ page, context }) => {
  await context.addCookies(authCookies);
  await context.route('**/*', (route) => {
    const url = route.request().url();
    if (
      url.includes('googletagmanager.com') ||
      url.includes('google-analytics.com') ||
      url.includes('googlesyndication.com') ||
      url.includes('clarity.ms') ||
      url.includes('doubleclick.net')
    ) {
      route.abort();
      return;
    }
    route.continue();
  });
});

for (const page of PAGES) {
  for (const vp of VIEWPORTS) {
    test(`${page.name} @ ${vp.name}`, async ({ page: pw }) => {
      await pw.setViewportSize(vp);
      // Hero selection and any A/B sampling must be deterministic in snapshots.
      await pw.addInitScript(() => { Math.random = () => 0; });
      const response = await pw.goto(BASE + page.path, { waitUntil: 'networkidle', timeout: 60_000 });
      expect(response && response.status(), 'Never accept an HTTP error as a baseline').toBe(200);
      expect(new URL(pw.url()).origin, 'Never screenshot a login or production redirect').toBe(new URL(BASE).origin);
      await expect(pw.locator('main')).toBeVisible();
      await expect(pw.locator('h1').first()).toBeVisible();

      // Wait for fonts (Noto Serif TC + Inter) to fully load
      await pw.evaluate(() => document.fonts.ready);

      if (page.name === 'home' || page.name === 'en-home') {
        await pw.waitForFunction(() => (
          window.DN &&
          [...document.querySelectorAll('#hs-article-list .article-list-item')]
            .filter(el => getComputedStyle(el).display !== 'none').length === 5
        ));
        await expect(pw.locator('.home-faq')).toBeVisible();
      }

      // Stabilise rendering:
      //   - kill all CSS animations / transitions / view-transitions
      //   - hide non-deterministic floating widgets (progress bar, scroll-to-top)
      //   - hide the EN banner timestamp on /en/ pages
      //   - freeze caret blink
      await pw.addStyleTag({
        content: `*, *::before, *::after {
          animation: none !important;
          transition: none !important;
          caret-color: transparent !important;
        }
        ::view-transition-old(*), ::view-transition-new(*) { animation: none !important; }
        #hs-progress-widget, #hs-totop, #hs-bookmark, #hs-print-btn, #hs-pwa-btn,
        #hs-pwa-ios, #hs-sw-toast, #hs-feedback, .hs-push-btn,
        [data-google-query-id], iframe[src*="googletagmanager"], iframe[src*="doubleclick"] {
          display: none !important;
        }
        /* Hide the relative-time badges (e.g. "5 days ago") that change daily */
        time[data-relative], .hs-relative-time { display: none !important; }`,
      });

      // A full-page screenshot must paint offscreen sections, rather than
      // comparing content-visibility placeholders whose intrinsic heights vary.
      // Keep the mobile above-the-fold capture under normal rendering rules.
      if (vp.name !== 'mobile') {
        await pw.addStyleTag({
          content: '.cv-auto, .cv-auto-short, .cv-auto-tall { content-visibility: visible !important; }',
        });
        // Full-page screenshots do not scroll: visit each viewport so the
        // site's own observers reveal cards and load deferred related content.
        const step = Math.floor(vp.height * 0.8);
        let reachedBottom = false;
        for (let y = 0; y <= 100_000; y += step) {
          reachedBottom = await pw.evaluate(top => {
            window.scrollTo(0, top);
            return window.scrollY + window.innerHeight >= document.documentElement.scrollHeight - 1;
          }, y);
          await pw.waitForTimeout(50);
          if (reachedBottom) break;
        }
        expect(reachedBottom, 'The full-page capture must visit the footer').toBe(true);
        if (page.article) {
          // Related content is fetched asynchronously and can move the footer.
          await expect(pw.locator('#hs-related a').first()).toBeAttached();
        }
        await pw.evaluate(() => document.fonts.ready);
        await pw.locator('footer').scrollIntoViewIfNeeded();
        await pw.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
        await expect.poll(() => pw.evaluate(() =>
          window.scrollY + window.innerHeight >= document.documentElement.scrollHeight - 1
        ), { message: 'Visit the final footer after deferred content and fonts settle' }).toBe(true);
        await expect.poll(() => pw.evaluate(() =>
          [...document.querySelectorAll('.reveal, .article-list-item, .myth-card')]
            .filter(el => el.getClientRects().length && Number(getComputedStyle(el).opacity) < 1)
            .length
        ), { message: 'Offscreen reader content must be revealed before capture' }).toBe(0);
        await pw.evaluate(() => document.fonts.ready);
      }

      // Scroll to top to standardise position, then settle
      await pw.evaluate(() => window.scrollTo(0, 0));
      await pw.waitForTimeout(700);

      const hasHorizontalOverflow = await pw.evaluate(() =>
        document.documentElement.scrollWidth > document.documentElement.clientWidth + 1
      );
      expect(hasHorizontalOverflow, `${page.name} @ ${vp.name} has horizontal overflow`).toBe(false);

      await expect(pw).toHaveScreenshot(`${page.name}-${vp.name}.png`, {
        // mobile = above-the-fold only (faster, less brittle to long-page changes)
        // tablet/desktop = full page
        fullPage: vp.name !== 'mobile',
        animations: 'disabled',
        timeout: 15_000,
      });
    });
  }
}
